spring:
  application:
    name: eurekaserver
  config:
    import: optional:configserver:http://localhost:8085

# Zipkin config
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Slf4j config
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"