services:

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 800m
    ports:
      - 9411:9411
    networks:
      - duquejo-network

  configserver:
    image: duquejo/configserver:latest
    mem_limit: 800m
    ports:
      - 8085:8085
    networks:
      - duquejo-network
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  eurekaserver:
    image: duquejo/eurekaserver:latest
    mem_limit: 800m
    ports:
      - 8065:8065
    networks:
      - duquejo-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  gatewayserver:
    image: duquejo/gatewayserver:latest
    mem_limit: 800m
    ports:
      - 8066:8066
    networks:
      - duquejo-network
    depends_on:
      - configserver
      - eurekaserver
      - hotels
      - rooms
      - reservations
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 3
        window: 100s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  hotels:
    image: duquejo/hotels:latest
    mem_limit: 800m
    ports:
      - 8080:8080
    networks:
      - duquejo-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  rooms:
    image: duquejo/rooms:latest
    mem_limit: 800m
    ports:
      - 8081:8081
    networks:
      - duquejo-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  reservations:
    image: duquejo/reservations:latest
    mem_limit: 800m
    ports:
      - 8082:8082
    networks:
      - duquejo-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

networks:
  duquejo-network: