apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms-deployment
  labels:
    app: rooms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rooms
  template:
    metadata:
      labels:
        app: rooms
    spec:
      containers:
      - name: rooms
        image: duquejo/rooms:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: duquejo-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: duquejo-configmap
              key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: duquejo-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: duquejo-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: rooms-service
spec:
  selector:
    app: rooms
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
